# Use the already built image as the base
FROM ghcr.io/richarddrochner/heybotrepo:latest

# Copy the Trivy scan output file into the image
COPY trivy_output.json /app/trivy_output.json

CMD ["python", "main.py"]