apiVersion: apps/v1
kind: Deployment
metadata:
  name: heybot-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heybot
  template:
    metadata:
      labels:
        app: heybot
    spec:
      containers:
        - name: heybot
          image: ghcr.io/richarddrochner/heybotrepo-with-trivy-output:1
          command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
          imagePullPolicy: Always
      imagePullSecrets:
        - name: heybotsecret  # Das ImagePullSecret, das du vorher erstellt hast
